### ISSUE TITLE
啥时候发布到utools市场呀？

### ISSUE THREAD

**Issue by Ahidada** [Zuoqiu-Yingyi/utools-siyuan#1]

**Comment by Zuoqiu-Yingyi** [comment]
上架 utools 插件应用市场要求 `proload.js` 文件在打包时不进行混淆, 但是我目前没找到使用 vite 或 rollup 进行生产环境构建时不对代码进行压缩与混淆的方案...

**Comment by Zuoqiu-Yingyi** [comment]
已发布到 utools 市场, 搜索 `思源笔记插件` 即可一键安装
