### ISSUE TITLE
设置没法保存

### ISSUE THREAD

**Issue by iamqiz** [Zuoqiu-Yingyi/utools-siyuan#5]
搜索设置>块类型,  保存之后,重新打开,还是之前的设置

**Comment by Zuoqiu-Yingyi** [comment]
能上传操作 录屏/Gif 吗, 我这里没法复现该问题👀

**Comment by iamqiz** [comment]
https://github.com/Zuoqiu-Yingyi/utools-siyuan/assets/48077521/555c6f2f-b259-46bf-910e-6f3127e1d3b9

**Comment by devick** [comment]
0.1.2版本还是有这个问题，和楼主发的适配一样，macos系统下

**Comment by Zuoqiu-Yingyi** [comment]
> 0.1.2版本还是有这个问题，和楼主发的适配一样，macos系统下

可能是配置不兼容的问题, 在 `我的插件应用` > `账号和数据` > `思源笔记插件` > `格式化` 中删除原配置试试
