### ISSUE TITLE
插件可能会因读写文件占用使SiYuan笔记崩溃

### ISSUE THREAD

**Issue by Reroll24** [Zuoqiu-Yingyi/utools-siyuan#6]
### 问题描述
插件可能会导致思源笔记崩溃。
![image](https://github.com/Zuoqiu-Yingyi/utools-siyuan/assets/41948123/3e7bd6f5-6b2f-4273-8fd8-976bbbb539e0)

- 该问题已出现多次
- 每次出现该问题后，在不关闭插件的情况下无法再次启动Siyuan笔记（均会弹出上述窗口）

### 用户实测可行的解决方案

1. 关闭（重启）插件/Utools
2. 可以正常启动笔记

### 推测可能的问题

- 插件读取Siyuan笔记的某些文件导致读写被占用。

**Comment by Zuoqiu-Yingyi** [comment]
应该不至于啊, 都是使用 API 与思源内核进行交互, 难道是分页数设置过大导致不稳定?
将 设置 -> 搜索设置 -> 分页数 设置为 1 后再试试能否复现该问题

**Comment by Reroll24** [comment]
今天遇到的时候，我发现在utools里强制关闭插件运行，还是会占用。必须得重启utools才能解决，不知道操作方法对不对。
![image](https://github.com/Zuoqiu-Yingyi/utools-siyuan/assets/41948123/f0b7a3d0-9739-4a12-bb1b-7d181174f789)

我再看看，平时搜索笔记的频率不是很高，所以问题不是很大，另外我的设置里分页数确实是1。
我也有点怀疑不会是别的插件占用了文件，但是检查下来好像没有什么插件与Siyuan有关，希望是乌龙吧（），好难排查。

~~设置的图想截好几次了，都上传不了，怪啊。~~

**Comment by Reroll24** [comment]
频率不是很高，今天才遇到。
但是遇到一个尴尬的情况，现在看起来好像不是因为这个插件导致的，我还是close掉吧
太尴尬了。
罪魁祸首是官方的本地搜索插件（基于Everything的那个）
抱歉打扰了（）我再想想办法看怎么解决那个插件的问题
