### ISSUE TITLE
能否兼容下浏览器地址呢

### ISSUE THREAD

**Issue by xibaoning** [Zuoqiu-Yingyi/utools-siyuan#7]
如题, docker部署, 不能siyuan://方式打开, 能否在utools开一个窗口来浏览内容呢

**Comment by Zuoqiu-Yingyi** [comment]
在设置中有一个选项指定 URI 格式

**Comment by xibaoning** [comment]
浏览器模式可以, 但体验有点割裂 渐进模式点击后没反应 如果能在utools窗口打开就非常好了(类似设置窗口)



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月15日(星期五) 下午2:01
收件人: "Zuoqiu-Yingyi/utools-siyuan";
抄送: "Author";
主题: Re: [Zuoqiu-Yingyi/utools-siyuan] 能否兼容下浏览器地址呢 (Issue #7)





 
在设置中有一个选项指定 URI 格式
 
&mdash;

**Comment by xibaoning** [comment]
太好了, 方便多了, 好像窗口的滚动条与思源的滚动条有点重合在一起了

**Comment by Zuoqiu-Yingyi** [comment]
> 好像窗口的滚动条与思源的滚动条有点重合在一起了

这是因为思源移动端页面没有定义滚动条的样式, 建议使用 CSS 代码片段自定义一下 `::-webkit-scrollbar` 样式

**Comment by xibaoning** [comment]
好像我没描述正确, 应该是页内小的块导航, 与utools滚动条重叠一起了, 不好点击



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月21日(星期四) 晚上10:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Zuoqiu-Yingyi/utools-siyuan] 能否兼容下浏览器地址呢 (Issue #7)





  
好像窗口的滚动条与思源的滚动条有点重合在一起了
  
这是因为思源移动端页面没有定义滚动条的样式, 建议使用 CSS 代码片段自定义一下 ::-webkit-scrollbar 样式

**Comment by xibaoning** [comment]
好像也不太对, 反正有2个滚动的东西重合一起了,我也不太懂




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月21日(星期四) 晚上10:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Zuoqiu-Yingyi/utools-siyuan] 能否兼容下浏览器地址呢 (Issue #7)





  
好像窗口的滚动条与思源的滚动条有点重合在一起了
  
这是因为思源移动端页面没有定义滚动条的样式, 建议使用 CSS 代码片段自定义一下 ::-webkit-scrollbar 样式

**Comment by xibaoning** [comment]
另外能否直接设置为PC模式嘛, 好像移动端模式功能操作上不太方便, 主要浏览文档时想左边的目录导航, 要反复来回点击

**Comment by Zuoqiu-Yingyi** [comment]
> 另外能否直接设置为PC模式嘛, 好像移动端模式功能操作上不太方便, 主要浏览文档时想左边的目录导航, 要反复来回点击

桌面端 UI 在小窗口中显示可能不还适合
